Feature/composer stable and gemfile
grrr-amsterdam/garp_scaffold pull request #17
Opened 2017-06-30 12:11 UTC by schoenkaft

- Added prefer-stable to Composer
- Updated ano/zf-twig to use `dev-master`
- Added Gemfile, so anyone can run `bundle install` to install dependencies (`semver` and `capistrano`)

2017-07-03 04:40 UTC, harmenjanssen requested changes
LGTM, maar er zijn conflicten! Als je die wegwerkt merge ik hem.

2017-07-03 08:08 UTC, schoenkaft commented
Dacht dat ik al gepulled had, blijkbaar niet. En blijkbaar was de change juist het aanmaken van een `Gemfile`. Dan komt er bij dezen nog `semver` bij in 😄

2017-07-04 04:45 UTC, harmenjanssen approved these changes

2017-07-04 04:45 UTC, merged

2017-07-04 04:45 UTC, harmenjanssen commented
Right on, LGTM!